### ISSUE TITLE
where is v5.0 nuget package and release notes?

### ISSUE THREAD

**Issue by abuassar** [appccelerate/statemachine#56]

**Comment by ursenzler** [comment]
v5.0 is still work in progress. There are a lot of changes in the API and I want to make sure that they are stable.

You can find the current alpha versions on the Appccelerate MyGet feed here: https://www.myget.org/feed/Packages/appccelerate

**Comment by ursenzler** [comment]
The changes in v5.0 are that you first have to build a state machine definition and then you can build a state machine from this definition.
That makes creating a state machine per request in Web API scenarios much quicker when holding the definition as a singleton).
A lot of internal structure was changes to allow building solutions for some feature requests. Mainly, tall internal state is hold by a single object so that saving and loading is much simpler.

**Comment by abuassar** [comment]
wonderful, I'm already evaluating an FSM lib for a web based app using dotnet core 3.0.

is there any rough estimation for when v5 will be ready?

**Comment by ursenzler** [comment]
You can use v5.0 alpha for production code. We are sure that the machine part works correctly. We are just getting some feedback about the API before releasing it as v5. Would be a shame to have to bump the version to 6.0 just because we missed something in the API. 

This is a spare time project, so no estimates available.

**Comment by ursenzler** [comment]
v5.1 is released on nuget.org, but documentation is not up-to-date yet. Please see the specs here in the repo on how to use the state machine - the API changed a lot.
https://github.com/appccelerate/statemachine/blob/master/source/Appccelerate.StateMachine.Specs/Async/Transitions.cs is a good example of how to use the state machine now.

**Comment by ursenzler** [comment]
rudimentary documentation is now included in readme.md, release notes directly in nuget package.
